name: Telecom_AutoRead

on:
  workflow_dispatch:
  schedule:
     - cron: '0 */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest    
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/YoToTelecom/YoTo.git ~/YoTo
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/YoTo
          npm install
          npm install cron
          npm install request
      - name: '运行 【Telecom_AutoRead】'
        run: |
          cd ~/YoTo   
          node Script/Telecom_YouAutoRead.js
